### ISSUE TITLE
Create convenience npm script to restart everything in the running container

### ISSUE THREAD

**Issue by jimmyhogoboom** [h2-open-source/ToxiChatBot#21]

**Comment by Dilden** [comment]
What exactly did we need with this? As it stands, if there is an error in the app, nodemon will watch the files and attempt to restart on save. I suppose if that doesn't work, there is `docker-compose restart` but I haven't run into a situation where I've needed that yet.

**Comment by jimmyhogoboom** [comment]
I did run into a situation where I had to restart because I changed an environment variable. I think `docker-compose` restart will be a fine solution.

**Comment by Dilden** [comment]
Oh interesting. Does nodemon not see those changes and restart the app? Could we include `.env` in the watching script?

**Comment by Dilden** [comment]
Looks like there are a few options

https://stackoverflow.com/questions/10560241/how-to-use-nodemon-with-env-files
